### ISSUE TITLE
env(safe-area-inset-top) / constant(safe-area-inset-top) reporting 0 on iPhone X

### ISSUE THREAD

**Issue by Screeze** [ionic-team/cordova-plugin-ionic-webview#49]
I'm trying to add iPhone X Support to my app. I updated all ionic and cordova packages and plugins, including the ionic-webview.  I added viewport-fit=cover to the meta tag.

However, I fail at getting the iPhone X to respect its safe areas now. The top notch is always covering my content.
I tried it with standard Pages which contain headers, which actually have several references to env(safe-area-inset-top) / constant(safe-area-inset-top), but also tried my custom in game screens with this constants added as padding. However, the app always behaves as if the values where 0. Adding manual padding would work (but influence other devices, for sure). But adding env(safe-area-inset-top) / constant(safe-area-inset-top) does not work, it just shows like padding:0;.

As far as I have read the webview should be supporting this, but I fail at getting it to work. I'm trying this in iPhone X simulator, iOS 11.1.

Any ideas?

```
> ionic info
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0
global packages:
    cordova (Cordova CLI) : 7.1.0 
local packages:
    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android ios 4.5.2
    Ionic Framework    : ionic-angular 3.9.2
System:
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    Node       : v6.10.3
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 
Environment Variables:
    ANDROID_HOME : not set
Misc:
    backend : pro
```

**Comment by Screeze** [comment]
Ok I just noticed something, it seems like a basic
padding-top: constant(safe-area-inset-top);
DOES work indeed.

BUT as soon as calc() gets involved, it does not:
padding-top: calc(constant(safe-area-inset-top)-5px);

So the issue seems to be in relation with "calc" only (for me the whitespace at the top is a bit too much so I tried adjusting it a bit in several ways)

**Comment by tobiasmuecksch** [comment]
I'm experiencing the same issue...

**Comment by sgrtho** [comment]
Hey, this may or may not be related, I'm experiencing a similar issue on iOS 11.2+, where all of our *constant* rules stopped working, independant of the *calc* expression.

But first of all, @Screeze: `calc(constant(safe-area-inset-top)-5px)` isn't a valid *calc* expression because `-` operator requires spaces, therefore: `calc(constant(safe-area-inset-top) - 5px)`.

But now using newer XCode builds I had to add `env(safe-area-inset-top)` rules throughout to get it working.

**Comment by tobiasmuecksch** [comment]
@sgrtho I've tried `constant` and `env`, because `constant` is deprecated in favor of `env` since iOS 11.2. But it still isn't working for me 👎

**Comment by tobiasmuecksch** [comment]
I fixed it. In my case there was `viewport-fit=cover` missing in the index.
With this meta tag it started working again:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
```

**Comment by Screeze** [comment]
Thanks for the hint with missing spaces, I wasn't aware of that and I will try it!
I used both, calc and env.

**Comment by dimitri320** [comment]
I'm struggling where to put this in the Ionic 3 files? Should this go inside the app.scss?

* {
  padding-top: constant(safe-area-inset-top);
  padding-top: env(safe-area-inset-top);
}

I've got the correct meta in my index file, but still not working (top and bottom is overlayed by iPhone X).

**Comment by lucaele** [comment]
same problem...

**Comment by jeggu96** [comment]
The IPhone X update has made its display such that the contents occupy all of the safe area that is available, thus giving a full screen view.

To support that feature:
We need to make the viewport fit the cover space of the screen.
`<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">`

Add this CSS to the main class of the page,
`padding: constant(safe-area-inset-top) constant(safe-area-inset-right) constant(safe-area-inset-bottom) constant(safe-area-inset-left);`[ <iOS 11.2 ]
`padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);` [ >iOS11.2 ]

**Comment by marutifh** [comment]
@jeggu96 

How did you manage to identify [ <iOS 11.2 ] or  [ >iOS11.2 ] in SCSS? Can you please share some inputs.

**Comment by jeggu96** [comment]
@marutifh If you want it to work on both all the iOS versions then you better add both the padding styles. If you really are focused on figuring out the iOS version, you can use jQuery, and add the respective classes.

**Comment by novokaine** [comment]
Alright, padding: env(safe-area-inset[where_you_want_it]) works in conjuction with <meta content="viewport-fit-cover"> - that will fix the web part. However, if you build a native IOS application (IPA file) out of you HTML/CSS using cordova - you end up with double padding. Seems like cordova is handling somehow this issue but you get double padding issue. Not sure how to handle it.

**Comment by aabdolla** [comment]
@novokaine Where did you add the padding? In app.scss like this?

    .platform-ios body {
        padding-top: constant(safe-area-inset-top); /* Status bar height on iOS 11.0 */
  	padding-top: env(safe-area-inset-top); /* Status bar height on iOS 11+ */
    }

**Comment by novokaine** [comment]
Yes, in the CSS. The env(safe-area-inset-top) gets ignored by other devices. 

Your code will look more like:
.header {
    padding-top: env(safe-area-inset-top); 
}

and don't forget the meta tag.

**Comment by aabdolla** [comment]
@novokaine So I have one page with just a ion-content wrapping it all. Do I still use .header when I don't have one? My main issue is an admob ad at the bottom.

**Comment by novokaine** [comment]
@aabdolla It depends on what type of modules and UI components you have within the application. I cannot say that setting this padding on .ion-content (which I guess is the main wrapper) will solve any problem that you have on IOS. What if you have fixed positioned elements, overlay menus and fixed footer - you have to treat them separately.

**Comment by moonbabygeng** [comment]
Checking the splash screen setting. Delete:
<img width="708" alt="screen shot 2018-03-28 at 11 20 24 am" src="https://user-images.githubusercontent.com/18367911/38039388-25af3a72-327b-11e8-89a0-c45bf9756236.png">
in config.xml.

**Comment by tricki** [comment]
I have the same problem but on non-X devices running iOS 11. I haven't tested on X yet.

- Main testing device: iPhone 6 with iOS 11.2.6
- XCode version: 8.2.1

What I already tried:
- `viewport-fit=cover` (adding or removing had no effect)
- updating ionic/cordova/statusbar plugin etc.

After some research I found these two statements that might point to the cause:

> Existing apps will continue working as they always have with no changes to their viewport behaviour. This only affects apps that are compiled with Xcode 9 and a target of iOS 11.
https://ayogo.com/blog/ios11-viewport/

> It turns out that safe-area-inset is 0 on iOS11 devices that are not the iPhone X.
https://www.quirksmode.org/blog/archives/2017/10/safeareainset_v.html

As I understand those the problem only occurs on non-X devices running iOS11+, and only for apps compiled with a target of less than 11. Unfortunately I can't target 11 right now since it would require an OS update.

Can anyone confirm this or have an idea how to fix it? Right now the only way I can think of is using `getComputedStyle` and add more padding if necessary, which isn't ideal.

**Comment by tfccomputation** [comment]
I only did this in app.scss

ion-navbar.toolbar.toolbar-ios.statusbar-padding, ion-navbar.toolbar-ios ion-title.title-ios,
ion-toolbar.toolbar.toolbar-ios.statusbar-padding, ion-toolbar.toolbar-ios ion-title.title-ios {
    padding-top: constant(safe-area-inset-top);
    padding-top: env(safe-area-inset-top);
}

**Comment by benmcmaster** [comment]
@novokaine did you find a clean solution to the double padding issue? I am getting double the bottom padding about 20% of the time I hard quit my app and reopen. Which is weird. When I remove `viewport-fit=cover` it's consistent and shows correct padding at the bottom of the app. Cordova must be putting it there as well. However when I remove `viewport-fit=cover` then `height: env(safe-area-inset-bottom);` always evaluates to 0px on iPhone XS running iOS 12.1.

**Comment by jcesarmobile** [comment]
I can't reproduce and looks like most people had the problem because of the missing `viewport-fit=cover`, so closing

**Comment by jake-moritz-trifecta** [comment]
I am getting the same issue as @benmcmaster. Ionic randomly adds padding to respect the safe area when the app starts. Sometimes the padding is there, sometime it is not. No clue why this inconsistent behavior is happening. `viewport-fit=cover` is in the index.html. Using wkwebview and Ionic 3.9.2.

**Comment by danielehrhardt** [comment]
I have the same Problem with my Android Phone.

I have added
`viewport-fit cover`

I use:
```
StatusBar.setOverlaysWebView({
      overlay: true,
    });
```
```
ion-app {
  top: 25px;
  top: constant(safe-area-inset-top);
  top: env(safe-area-inset-top);
}
```

**Comment by antonioberetini** [comment]
How about safe-area-inset-bottom? For instance, since android 10, users are defaulted to gesture navigations similar to i OS which introduces minimal navigation bar. I noticed that height is not passed in this case, see my attachment. Top reports just fine but bottom does not, causing footer component to sink into the navbar area.

![Screenshot_20210801-094729~2](https://user-images.githubusercontent.com/65619488/127775291-1aaa8a40-fa2e-4eef-86f0-1b5bfc10bb4b.png)

**Comment by Aihabam** [comment]
Use `  <ion-toolbar>` inside the footer.
